-- MySQL Script generated by MySQL Workbench
-- Wed Nov 19 09:23:10 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pmb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pmb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pmb` DEFAULT CHARACTER SET utf8 ;
USE `pmb` ;

-- -----------------------------------------------------
-- Table `pmb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmb`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmb`.`Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL,
  `dateHeure` DATETIME NOT NULL,
  `amount` DOUBLE NOT NULL,
  `sender_idUser` INT NOT NULL,
  `receiver_idUser` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  UNIQUE INDEX `idTransaction_UNIQUE` (`idTransaction` ASC) VISIBLE,
  INDEX `fk_Transaction_User_idx` (`sender_idUser` ASC) VISIBLE,
  INDEX `fk_Transaction_User1_idx` (`receiver_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_User`
    FOREIGN KEY (`sender_idUser`)
    REFERENCES `pmb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_User1`
    FOREIGN KEY (`receiver_idUser`)
    REFERENCES `pmb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pmb`.`Connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pmb`.`Connection` (
  `User_idUser` INT NOT NULL,
  `User_idUser1` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `User_idUser1`),
  INDEX `fk_Connection_User2_idx` (`User_idUser1` ASC) VISIBLE,
  CONSTRAINT `fk_Connection_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `pmb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Connection_User2`
    FOREIGN KEY (`User_idUser1`)
    REFERENCES `pmb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
